### ISSUE TITLE
Add cache for CI builds

### ISSUE THREAD

**Issue by scc-tw** [25077667/standalone-python#1]
## Issue Details

The current Continuous Integration (CI) process for Docker builds in our project does not utilize caching mechanisms. This leads to increased build times as each build process starts from scratch, downloading and rebuilding all dependencies and layers. Implementing caching could significantly reduce the build times and resource usage, making our CI/CD pipeline more efficient.

### Docker Layer Caching

1. **Enable Docker Buildx**  
   Update the GitHub Actions workflow to use Docker Buildx, which supports advanced build caching options.
   
   ```yaml
   - name: Set up Docker Buildx
     uses: docker/setup-buildx-action@v2
   ```

2. **Configure caching in Buildx**  
   Modify the Docker build step to use the `--cache-from` and `--cache-to` options to leverage caching of layers.
   
   ```yaml
   - name: Build docker image
     run: |
       docker buildx build \
         --load \
         --cache-from type=local,src=/tmp/.buildx-cache \
         --cache-to type=local,dest=/tmp/.buildx-cache-new \
         -t my-image-name:${{ github.sha }}
         .
   ```

3. **Persist Buildx cache**  
   Use GitHub Actions cache to save and restore Buildx cache directory.
   
   ```yaml
   - name: Cache Docker layers
     uses: actions/cache@v3
     with:
       path: /tmp/.buildx-cache
       key: ${{ runner.os }}-buildx-${{ github.sha }}
       restore-keys: |
         ${{ runner.os }}-buildx-
   ```

### Caching Dependencies

1. **Cache dependencies explicitly**  
   If your project uses dependency managers (like npm, Maven), configure caching for these tools explicitly in the GitHub Actions workflow.

   ```yaml
   - name: Cache Node modules
     uses: actions/cache@v3
     with:
       path: ~/.npm
       key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
       restore-keys: |
         ${{ runner.os }}-node-
   ```

### CI Configuration Adjustments

1. **Integrate caching into CI/CD pipeline**  
   Revise the `.github/workflows/ci.yml` file to include the above caching configurations.

2. **Monitor and fine-tune caching**  
   Continually monitor the caching effectiveness in the Actions logs and adjust configurations to optimize cache hits.

## Expected Benefits

- **Reduced Build Times**: Caching will decrease the time taken for CI builds by leveraging previously built and cached layers and dependencies.
- **Cost Efficiency**: Using less computational resources per build will lower the overall cost associated with CI.
- **Improved Developer Productivity**: Faster build times mean quicker feedback cycles, enhancing developer productivity and workflow.

## Actions

1. **Review the proposed caching strategies**  
   Discuss and review these changes with the development team to ensure they align with our project goals and infrastructure.

2. **Implement in a test branch**  
   Apply these changes in a test branch and execute multiple builds to measure the impact and effectiveness of the caching mechanisms.

3. **Merge and monitor**  
   If the test results are satisfactory, merge the changes to the main branch and continue to monitor build times and resource usage, ready to make further adjustments as needed.
